# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

version: '3.7'

services:
  pman_service:
    # During dev pman needs access to the pfioh storeBase folder (and hence the volume)
    # mapping from the HOST file system space to be able to run the tests. This is not
    # necessary for a production pman.
    #
    # Since pman spins off containers of its own it needs to mount storeBase dir (where
    # pfioh shares the data) into the spawned container. However, it can't mount a dir
    # inside itself to the spawned container, it has to mount an actual existing
    # directory in the host. This directory is passed in the STOREBASE env variable.
    environment:
      - STOREBASE
    image: ${PMANREPO}/pman:dev
    command: ["--ip", "0.0.0.0", "--verbosity", "1"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./FS/remote:/home/localuser/storeBase:z
      - ./pman:/home/localuser/pman/pman:z
      - ./bin:/home/localuser/pman/bin:z
      - ./tests:/home/localuser/pman/tests:z
    ports:
      - "5010:5010"
    labels:
      name: "pman"
      role: "pman service"
